### ISSUE TITLE
ConsistentFormat

### ISSUE THREAD

**Issue by rsryman** [rryman/BB4-Worksheets#1]
1. Update Acknowledgements and Footer; Add/update "TM" on p. 2 (Option+2)
2. Consistent format for section title: e.g.,**Positions of the Feet** (_Book 1_ Summary p. #/pp. #).
3. Label above the corresponding BMN clip, followed by a colon only if there is more info, e.g. 1st: flat/demi-pointes/pointes. 12 pt; label below 10 pt
4. Try to keep font size consistent
5. For empty staves, add solid start/end stave bar line (instead of dashed bar line)
6. Use superscript re 1st/2nd/3rd/4th/5th
7. Where needed, place "continued" after title/before page reference, e.g., BB2 Worksheet p. 7: Movement Lines continued (Book 2 p. 13)
8. Go through text to eliminate redundant instructions)

**Comment by rsryman** [comment]
To be discussed re: 
[BB4WorksheetsPP1-93.pdf](https://github.com/rryman/BB4-Worksheets/files/2386845/BB4WorksheetsPP1-93.pdf)
1. Date of footer: October 2018?
2. Discuss content of Ch2-4 BB10-12 (without in-stave info) See suggestions on Worksheet pp. 4-8: Robyn to take graphics from **Book 4** iba file? As a working method, I tried to take a screen dump of each sign cluster from Ibook Author and insert it as a place marker but Word 6 only recognizes PICT TIFF EPS. Suggestions?  
3. When introducing locomotion lines, I suggest we add a stave with locomotions lines omitted to as students to add only the locomotion lines, then an empty stave to recopy all?
4. When same side repeats are written out as on _Book 4_ pp. 78-79 no need to recopy? See Worksheets p. 12. But recopy for other side repeat as _Book 4_ p. 82, for practice re travel R/L, yes?
5. In this set of worksheets, is it necessary to keep labeling "Starting R ft vs L ft"? This should be understood by now? On some pages with 8 notation staves (e.g., Worksheets p. 15) there is no room to add below-stave labels. Labels added on p. 16 since runs are tricky, yes? Other pages to be discussed?

**Comment by rryman** [comment]
November 2018 is probably more realistic.

**Comment by rryman** [comment]
When you take a screen dump it should save the file as .png.
1. Open the .png file with Preview
2. Export the file as either TIFF or JPEG

**Comment by rryman** [comment]
When introducing locomotion lines, I suggest we add a stave with locomotions lines omitted to as students to add only the locomotion lines, then an empty stave to recopy all?

**This is an excellent idea!**

**Comment by rryman** [comment]
When same side repeats are written out as on Book 4 pp. 78-79 no need to recopy?

**I would give them the option to write out even the same side repeat info.**

**Comment by rryman** [comment]
I agree you don't need the right and left info unless it is confusing, like runs, etc.

**Comment by rryman** [comment]
Page 3:

Reword to make this intro more relevant to Book 4?
What about something along the lines of ...

These worksheets are intended to give you practice writing Benesh Movement Notation (BMN).
This will help you master BMN principles for staging information.
There is no need to complete every question. Rather, complete as much of each lesson as you feel you need to master the new signs introduced.
If you feel confident, you may copy any of the examples onto red-lined stave paper.
A printable pdf is provided at the end of these worksheets.
In order to reinforce your ability to read BMN, where applicable, you should stand up and perform each sequence before attempting to copy it.
Don't copy blindly, but rather make sure you understand the notated sequence and the relevant Benesh theory.

**Comment by rryman** [comment]
Page 4: add info about bar lines and repeat signs?

Neatness is important. Although the ultimate goal is to write the notation freehand, you may use
a ruler to draw Benesh signs where necessary until you master them. **Remember to use a ruler to draw all bar lines and repeat signs.**

**Comment by rryman** [comment]
Page 4:

ROBYN TO INSERT GRAPHIC OF P. 7 STAGE PLAN AT BOTTOM RIGHT (+ signs & labels)

Just to clarify were you thinking something like:

[StagePlanLocations.pdf](https://github.com/rryman/BB4-Worksheets/files/2386934/StagePlanLocations.pdf)

**Comment by rryman** [comment]
Page 4:

ROBYN TO INSERT GRAPHIC OF P. 7 STAGE PLAN AT BOTTOM RIGHT (+ signs & labels)

Just to clarify were you thinking something like:

[StagePlanLocations.pdf](https://github.com/rryman/BB4-Worksheets/files/2386958/StagePlanLocations.pdf)

**Comment by rryman** [comment]
Page 5:

Something like:
[OnLocationPlan.pdf](https://github.com/rryman/BB4-Worksheets/files/2386967/OnLocationPlan.pdf)

**Comment by rryman** [comment]
Page 5 typo:

The tick is placed at the right of the location sign to indicate “right of the location” upstage or
**downsatge**. Copy each location sign directly below the stage plan.

**Comment by rryman** [comment]
Before I do graphics for BB4 pages 9 - 12, let's decide on size and format of the two examples above.

**Comment by rryman** [comment]
I suggest for BB4 Page 14:

Suggested text:
Identification heads on direction signs are used to show more than one dancer of a stage plan. Look at the stage plan and notate the appropriate location and identification sign below each notated position.

Suggested graphics and notation:
I'll use the graphic on BB4 page 14. Under it will be the 5 frames of notation without the location and direction signs.

**Comment by rryman** [comment]
BB4 Page 16:

Heading:
Other Descriptions for Location Signs (_Book 4_ p. 16)

Suggested text:
Copy the poses and locations from the _RAD Set Exercises and Variations_ notated below.

Layout the notation as Location and In-Stave Information above. Using headings - corner 5, en face etc.

**Comment by rryman** [comment]
I think that we should skip straight to BB4 page 22.
Just have the general travel sign and how it is broken into the four basic travel signs.
I can copy the graphics from BB4 and lay it out the same way, adding a third column with the travel signs greyed out.

Title: Introduction to Travel

Text: 
The general travel sign is an arrow consisting of a shaft, head, and tail. Travel proceeds from
the tail, along the shaft toward the head. The general travel sign is broken into four basic travel signs: forward, backward, sideways right and sideways left. Trace the grey notation of the four basic travel signs in the chart on the right.

Graphics: General travel sign, 4 basic travel signs with text, text with no travel signs

**Comment by rryman** [comment]
[17:09:2018-BB4Worksheets-PP1-93.pdf](https://github.com/rryman/BB4-Worksheets/files/2390185/17.09.2018-BB4Worksheets-PP1-93.pdf)

**Comment by rryman** [comment]
[BB4Worksheets-P5.pdf](https://github.com/rryman/BB4-Worksheets/files/2390212/BB4Worksheets-P5.pdf)

**Comment by rsryman** [comment]
From here on, for all unresolved comments above Rhonda to open separate issues.
