### ISSUE TITLE
Most recent version of BB4 Worksheets

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#11]
This is the most recent version of BB4 Worksheets I could find on GitHub.
Rhonda, please use this issue to keep the most recent version of the file updated.
It is hard for me to find it when it is buried amid all the other issues.
Thanks!

[BB4WorksheetsOct15.2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2487701/BB4WorksheetsOct15.2018.pdf)

**Comment by rsryman** [comment]
[BB4WorksheetsOct18,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2492788/BB4WorksheetsOct18.2018.pdf)

**Comment by rsryman** [comment]
[BB4WorksheetsOct19,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2497282/BB4WorksheetsOct19.2018.pdf)

**Comment by rsryman** [comment]
This update includes revisions up to and including Issue #29. 
[BB4WorksheetsOct23,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2508049/BB4WorksheetsOct23.2018.pdf)

We go to the ROM tomorrow, so I'll resume on Thursday.

**Comment by rryman** [comment]
Okay. When you have answered Issues #32 and 33 I will continue, as decisions have to be made before I move forward.
In the meantime, I can go back and work on any of the graphics I haven't already input in my separated pages.

**Comment by rsryman** [comment]
[BB4WorksheetsOct24,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2512472/BB4WorksheetsOct24.2018.pdf)

**Comment by rsryman** [comment]
Updates re Worksheets pp. 20-22
[BB4WorksheetsOct25,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2519650/BB4WorksheetsOct25.2018.pdf)

**Comment by rsryman** [comment]
Format of labels & captions updated:
[BB4WorksheetsOct26,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2519938/BB4WorksheetsOct26.2018.pdf)

**Comment by rsryman** [comment]
I think the only remaining thing to agree on is the phrase I suggested deleting on p. 16: "around the facing front direction sign"
[BB4WorksheetsOct27,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2521896/BB4WorksheetsOct27.2018.pdf)

**Comment by rsryman** [comment]
Completed updates to Issue #46 (to p. 38):
[BB4WorksheetsOct29,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2527484/BB4WorksheetsOct29.2018.pdf)

**Comment by rsryman** [comment]
Revisions re Issue #47:
[BB4WorksheetsOct30,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2530273/BB4WorksheetsOct30.2018.pdf)

**Comment by rsryman** [comment]
Updates to pp. 37-38 ("the ebook" -> _Book 4_):
[BB4WorksheetsNov14,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2582491/BB4WorksheetsNov14.2018.pdf)

**Comment by rsryman** [comment]
[BB4WorksheetsNov19,2018.pdf](https://github.com/rryman/BB4-Worksheets/files/2596982/BB4WorksheetsNov19.2018.pdf)

**Comment by rsryman** [comment]
[BB4WorksheetsJan27,2019.pdf](https://github.com/rryman/BB4-Worksheets/files/2800408/BB4WorksheetsJan27.2019.pdf)

**Comment by rsryman** [comment]
[BB4WorksheetsFeb4,2019.pdf](https://github.com/rryman/BB4-Worksheets/files/2829668/BB4WorksheetsFeb4.2019.pdf)

**Comment by rsryman** [comment]
With updates fonts for tempo, time signature, and repeats numerals:
[BB4WorksheetsFeb6,2019.pdf](https://github.com/rryman/BB4-Worksheets/files/2837553/BB4WorksheetsFeb6.2019.pdf)

I'll open a new issue re adding two new pages before the empty staves.

**Comment by rsryman** [comment]
[BB4WorksheetsFeb7,2019.pdf](https://github.com/rryman/BB4-Worksheets/files/2842515/BB4WorksheetsFeb7.2019.pdf)

**Comment by rryman** [comment]
Robyn has updated pages 1-7 (inclusive) in BB4Worksheets7FebP7.pdf

- [ ] Rhonda to proofread

[BB4Worksheets7FebP7.pdf](https://github.com/rryman/BB4-Worksheets/files/2842727/BB4Worksheets7FebP7.pdf)

**Comment by rryman** [comment]
Robyn has updated pages 8-17 (inclusive) in BB4Worksheets8FebP17.pdf

[ ]  Rhonda to proofread

[BB4Worksheets8FebP17.pdf](https://github.com/rryman/BB4-Worksheets/files/2845263/BB4Worksheets8FebP17.pdf)

**Comment by rsryman** [comment]
Everything fine to p. 17 except the BMN frames to be greyed: see Issue #62

**Comment by rryman** [comment]
Robyn has updated pages 18-23 (inclusive) in BB4Worksheets8FebP23.pdf

[ ] Rhonda to proofread

[BB4Worksheets8FebP23.pdf](https://github.com/rryman/BB4-Worksheets/files/2846251/BB4Worksheets8FebP23.pdf)

**Comment by rsryman** [comment]
All correct except 3 typos: Robyn, see Issue #63
