### ISSUE TITLE
New BB4_P19 (Book 4 p. 53)

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#29]
Here is my suggestion for a new page 19. This will change the pagination from this page forward, so I won't do any further work on BB4 worksheets until you have adjusted the original document and post the updated document to GitHub.

[BB4P19.pdf](https://github.com/rryman/BB4-Worksheets/files/2502661/BB4P19.pdf)

**Comment by rryman** [comment]
With the stage plan centred as discussed in the BB4_P18 issue.
[BB4P19.pdf](https://github.com/rryman/BB4-Worksheets/files/2507455/BB4P19.pdf)

**Comment by rsryman** [comment]
Layout fine. I didn't realize you opened a new issue for p. 19 so I answered re p. 18.

**Comment by rsryman** [comment]
Done.
