### ISSUE TITLE
ItalicizationOfTerms

### ISSUE THREAD

**Issue by rsryman** [rryman/BB4-Worksheets#3]
Below is a list of terms to be italicized. 
Rhonda to keep updating this comment as terms are added and do a global check of final .doc file before final export to pdf file for Robyn.

_location_ sign
_locomotion_ line
_movement_ line
_repeat_ sign
_stage plan_
_travel_ sign

**Comment by rryman** [comment]
Also ...

_entrance_ sign
_exit_ sign

**Comment by rryman** [comment]
Also ...

_jump_ lines
_step_ lines
_slide_ lines

**Comment by rsryman** [comment]
I went through this entire list and found only 2 oversights:

- [ ] Robyn to update pdf file

- [ ] Rhonda to update .doc file

p. 16: Note that each _diagonal travel_ sign

p. 24: to the accurate drawing of _movement_ lines and, ….

QUESTION: We do not italicize these terms in the blurb on p. 50. I think this should stay as is.

**Comment by rryman** [comment]
Updated in the attached pdf:
[BB4Worksheets8FebP25.pdf](https://github.com/rryman/BB4-Worksheets/files/2846694/BB4Worksheets8FebP25.pdf)

I purposely didn't italicize them in the blurb so that the italicized _Book x_ would stand out.

**Comment by rryman** [comment]
Please do not close this issue, as I will add to this list if I notice any other terms italicized.
