### ISSUE TITLE
New BB4_P20 (Book 4 pp. 55 and 56)

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#32]
**New page 20**
[BB4_P20.pdf](https://github.com/rryman/BB4-Worksheets/files/2507745/BB4_P20.pdf)

Please look at the heading, text, layout, and sizes of the signs on this new page.
I think it makes the most sense to agree on this page before I create the next page for the sideways right and left travel.

**Comment by rsryman** [comment]
Your layout is clear but perhaps the chart format (bounding boxes) isn't necessary? I recreated it as close as possible but can't remember how I fudged the superscript fraction (1/2). Can you tweak it in AI? If this is OK, I will do the same for p. 21 re sideways travel.
[BB4p20.pdf](https://github.com/rryman/BB4-Worksheets/files/2511904/BB4p20.pdf)

**Comment by rsryman** [comment]
Updated as per our phone call: captions left aligned, fractions plain text.

Robyn to add chart lines.
