### ISSUE TITLE
Next steps - New page 21 onwards

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#33]
Suggestion:

**New page 21** - sideways right and left travel (Book 4 pp. 57-58)
Heading: Curved Path of Travel Sideways and Brackets?
Instructions: Pay special attention to the placement of the tick indicating sideways left and right, as in straight travel. (Is this all we will need?)
Graphics: Chart with eight entries - layout similar to new page 20.

**New page 22** - other shapes and entrance and exit (Book 4 pp. 59-60)
Heading 1: Curved Path of Travel - Other Shapes
Instructions: any needed?
Graphics: Chart with two entries.

Heading 2: Curved Travel with Entrance and Exit
Instructions: Copy this sequence in the space provided below. Note that only two locations are needed to specify the diameter of the circle.
Graphics: No chart - just the example from Book 4 page 60 with space underneath.

**New page 23** - Correlating Stage Plans with Music Bars (Book 4 pp. 61-62)
Heading: Correlating Stage Plans with Music Bars
Instructions: Draw the direction, location, and travel signs in the empty stage plans to reflect the staging information given below each stage plan.
Graphics: Nine empty stage plans with the music bar numbers and the BMN staging instructions below each plan.

**New page 24** - CHAPTER 5: Benesh Basics 13 (which is the old page 20 in the BB4WorksheetsOct22.2018.pdf). 

I don't think there should be any further pagination changes after these updates are implemented.

**Comment by rryman** [comment]
Rhonda, if you agree with the suggestions above please update the pages and text in your word doc and I will add the graphics to the updated doc.

**Comment by rryman** [comment]
Where is the Oct24 PDF?

---

**Comment by rsryman** [comment]
Just finished working on it. Will upload before I make supper.
