### ISSUE TITLE
BB4_P22 (Book 4 p. 59 & 60)

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#41]
1)
When drawing travel signs for other curved paths, visualize the start and end of the path, then
draw the appropriate tick at the head of the arrow for travel forward or **back** or the tail of the
arrow for travel sideways left or right.

We always say **backward** (not back).

2)
Copy this sequence in the space provided **below.Note** that only two locations are needed to
specify the diameter of the circle.

Space between "below." and "Note"

3)
Please looks at the pdf and let me know if you want anything changed.
Wasn't sure where to centre or left justify the entrance and exit graphic.
Either way looked much of a muchness. I am happy to left align it if you'd prefer.

[BB4_P22.pdf](https://github.com/rryman/BB4-Worksheets/files/2520806/BB4_P22.pdf)

**Comment by rsryman** [comment]
Updates made to text. I like this page layout as is.
