### ISSUE TITLE
Robyn's Proofreading of Oct. 27th Doc - Up to but not including BB4 Worksheets p. 10

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#43]
I am going to proofread the entire document before attempting to add the graphics and fix the notation. I will make one entry per page in this issue so Rhonda can go through them and tick them as she completes them.

I suggest Rhonda start a new issue if any of the suggestions need discussion. Open a new issue per response so we can deal with it and then close the issue.

Rhonda, you may want to wait until I have completed proofreading the entire document before you edit at your end as this may take me awhile.

**Comment by rryman** [comment]
- [ ] Acknowledgements - typo in bold:
The authors **wih** to gratefully acknowledge the proofreading assistance of Canan Kayacik, Istanbul University State Conservatory, Department of Performing Arts, Ballet Department, Artist Faculty.

**Comment by rryman** [comment]
- [ ] Instructions p. 3 - update instructions to reflect content of Book 4 or just leave it as **each position**?
In order to reinforce your ability to read BMN, you should stand up and perform **each position** before attempting to copy it.
Don't copy blindly, but rather make sure you understand **each position** notated and the relevant Benesh theory.

Maybe replace with "the sequences"?

**Comment by rryman** [comment]
- [ ] p.5 & p.6
What do you think about bolding:
centred, right, left, and between
in each of the instructions so these differences are highlighted?

i.e.,
Take note that the short line (tick) is **centred** along the location sign to indicate the person’s placement upstage/downstage, and that the tick is always drawn horizontal and not at a right angle to the location sign.

Note that the tick is drawn horizontal and placed at the **right** of the location sign.

Note that the tick is drawn horizontal and placed at the **left** of the location sign.

Note that adjacent location signs are drawn as close together as possible, maintaining the clarity of the tick which is drawn horizontal and placed **between** them.

**Comment by rryman** [comment]
- [ ] p. 8 - repetitive instructions? - delete bolded sentence?
The _location_ sign is placed below corresponding in-stave notation, just left of the _direction_ sign if it is included, or centred below the frame if it is not. **Copy each example in the empty frames provided.** Remember that the head of the _direction_ sign is centred below the frame.

Copy each example in the space provided to its right, paying careful attention to the placement of the _direction_ and _location_ signs in relation to the dotted centre line. Start by tracing the grey notation (the Benesh signs only, not the stave lines or bar lines), then recopy each position into the frames with and without a dotted centre line.

**Comment by rryman** [comment]
- [ ] p. 8 - typo - bold below
Facing stage right, **neat** the back, right wing quarter

**Comment by rryman** [comment]
p. 8 - notation correction

- [ ] For "Facing downstage left on frontmost edge, left wing quarter" the notation has the incorrect legs - should be standing on right with left leg in arabesque.

- [ ] For "Facing downstage right, midway between middle and back, left of left half" - 
should be medium turn of head not max?

- [ ] For "Facing downstage left, midway between middle and front, between right centre quarter and right half -
should be medium turn of head not max?

- [ ] For "Facing stage right, near the back, right wing quarter"
placement of the tick on the location sign should be lower as it is "near the back" not "midway between middle and back"

**Comment by rryman** [comment]
p. 9 - incorrect number

- [ ] Add the appropriate _location_ and identifying _direction_ sign below each notation frame to match the **six** identification signs, from left to right, on the stage plan.
- should be **five**

**Comment by rryman** [comment]
p. 9 - incorrect notation

- [ ] first frame - wrong leg
- [ ] second frame - medium turn of head
- [ ] third frame - arms in second
- [ ] 4th frame - medium turn of head

**Comment by rsryman** [comment]
Agreed.

**Comment by rsryman** [comment]
RHONDA has made all suggested edits for Robyn to double check. No further issues re the above.

**Comment by rryman** [comment]
Only one not fixed:
p. 9 - incorrect notation
second frame - medium turn of head

You changed the head on page 8, but not on page 9.

**Comment by rsryman** [comment]
Done.
