### ISSUE TITLE
Robyn's Proofreading of Oct. 27th Doc - Starting at BB4 Worksheets p. 28 up to (but not including) p. 39

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#46]
- [x] p. 30 - missing jump line
First example, Bar 2, Count 2-3

- [x] p. 31 - take out locomotion lines
Stave 3

- [x] p. 32 - height of level signs for "arms by side"
Specific Versus Non-Specific Timing - Natural Walks (Book 4 p. 85)
In 4 places - move the levels signs so they are in the middle of the space from waist to knee
(I think it is only one pixel down).

- [x] p. 33 - incorrect notation
Specific Versus Non-Specific Timing - Courus Sur Place (Book 4 p. 87)
1st full pointes - first and closing first signs need to be sitting on the line and ad lib signs need to be just above the floor line

- [x] p. 34 - title incorrect
Specific Versus **Specific** Timing - Courus en Tournant (_Book 4_ p. 88)
Should be:
Specific Versus **Non-Specific** Timing - Courus en Tournant (_Book 4_ p. 88)

- [x] p. 34 - incorrect notation
Specific Versus Non-Specific Timing - Courus Travelling (_Book 4_ p. 89)
Last example - 5th position incorrect - should be right foot front

- [x] p. 35 - location signs - horizontal tick too far downstage
centre downstage mid-way between middle and front
right centre quarter mid-way between middle and front

- [x] p. 35 - incorrect notation
Path of Travel Determined by In-Stave Information (Book 4 p. 92)
starting position incorrect - should be right foot in front

- [x] p. 36 - Rhonda reworded the explanation for the two notation versions.
Robyn to check it when final edits are done.

- [x] p. 36 - incorrect notation
Starting positions in both examples incorrect. Should be right foot in front.
Robyn to fix location signs to match ebook.

- [x] p. 37 - incorrect notation 
First example - galop: left bent level knee missing on count 2

- [x] p. 37 - rewording
Dimensions of Circular Travel (Book 4 p. 95)
Rhonda reworded the explanation - Robyn to check it.

- [x] p. 37 - incorrect notation
Both Scherzo examples - ending position should be straight right back leg
Both examples - location signs should join (Rhonda to try to fix it, if not Robyn will)

- [ ] p. 38 - rewording
Dimensions of Other Paths of Travel (Book 4 p. 96)
Rhonda reworded the explanation - Robyn to check it.

- [x] p. 38 - incorrect notation
Both examples - starting position should be right leg attitude a terre
Both examples - should be Scherzo and not Moderato

**Comment by rsryman** [comment]
Re p. 30: delete "Remember to use a ruler to draw bar lines as needed in the empty staves provided" since we just said that on p. 27 -- or retain as a reminder?

Re p. 37: I fixed the end positions but not the stage location signs: moving them even 1 pixel closer makes the horizontal ticks touch; ROBYN TO FIX

**Comment by rryman** [comment]
Re p. 30: delete "Remember to use a ruler to draw bar lines as needed in the empty staves provided" since we just said that on p. 27 -- or retain as a reminder?

Yes, please delete it.

**Comment by rryman** [comment]
The instructions on page 38 are repetitive. What do you think about removing them?

If you decide not to remove the instructions on page 38, how about making the sentence the same on pages 37 and 38? At the moment they are different:
P. 37:
Note that the first example is shrunk slightly to fit on one stave.
P. 38:
The first example is slightly shrunk to fit on one stave.

I suggest:
**The first example is shrunk slightly to fit on one stave.**

**Comment by rsryman** [comment]
Since there is room and because the bottom example is not in Book 4, let's leave the repeated instructions here, updated as "shrunk slightly." If Canan finds it repetitive, we can delete it.
