### ISSUE TITLE
Robyn's Proofreading of Oct. 27th Doc - Starting at BB4 Worksheets p. 39 up to (and including) p. 51

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#47]
- [x] p. 39 - location sign missing and extra ending bracket
Curved Travel with Entrance and Exit (Book 4 p. 97)
Count 14 needs a midway between middle and front on left half location sign
Delete ending bracket under the dotted line of the same bar

- [x] p. 40 - rewording
Rhonda has reworded the instructions at the top of this page.
Robyn to proofread

- [x] p. 40 - notation different
Travel Forward (Book 4 p. 104)
Anacrusis - delete aerial position (5th position in the air is not in Book 4)

- [x] p. 41 - notation different
Travel Forward continued (Book 4 p. 104)
Anacrusis - delete aerial position (5th position in the air is not in Book 4)

- [ ] p. 41 - join location
Robyn to join location in Adobe Illustrator

- [x] p. 41 - notation correction
Starting position - level signs to be centred between waist and knee lines

- [x] p. 41 - notation correction
Count 2 - step line to left back foot

Travel Backward continued (Book 4 p. 105)
- [x] p. 42 - notation correction
Starting position - level signs to be centred between waist and knee lines

- [x] p. 42 - notation correction
Count 2 - step line to left back foot

Travel Sideways Right continued (Book 4 p. 106)
- [x] p. 43 - notation correction
Summary locations is missing left half location - match Book 4 example?

Travel Diagonally to Corners (Book 4 p. 108)
- [x] p. 45 - notation different
In both examples: Anacrusis - delete aerial position (5th position in the air is not in Book 4);
take out pulse beat and legato line

- [x] p. 45 - notation correction
Top example, end of stave 1 - travel sign cut off

Travel Diagonally to Corners continued (_Book 4_ p. 108)
- [x] p. 46 - notation different
In both examples: Anacrusis - delete aerial position (5th position in the air is not in Book 4)
take out pulse beat and legato line

Travel Diagonally to Corners continued (_Book 4_ p. 109)
- [x] p. 47 - notation different
Anacrusis - delete aerial position (5th position in the air is not in Book 4) and pulse beat and legato line
Bar 2, Bar 4, and Bar 6 - delete aerial position (5th position in the air is not in Book 4), pulse beat, and legato line, and shorten jump line

- [x] p. 47 Beginning  of stave 1 - travel sign cut off

Travel Diagonally to Walls (Book 4 p. 110)
- [x] p. 48 - notation different
In both examples: Anacrusis - delete aerial position (5th position in the air is not in Book 4)
take out pulse beat and legato line

- [x] p. 48 - notation correction
Top example, end of stave 1 - travel sign cut off

Travel Diagonally to Walls continued (Book 4 p. 110)
- [x] p. 49 - notation different
In both examples: Anacrusis - delete aerial position (5th position in the air is not in Book 4)
take out pulse beat and legato line

- [x] p. 48 - notation correction
Top example, end of stave 1 - travel sign cut off

Travel Diagonally to Walls (_Book 4_ p. 111)
- [x] p. 50 - notation different
Anacrusis - delete aerial position (5th position in the air is not in Book 4) and pulse beat and legato line
Bar 2, Bar 4, and Bar 6 - delete aerial position (5th position in the air is not in Book 4), pulse beat, and legato line, and shorten jump line

**Comment by rryman** [comment]
P. 45 - Colon missing after OPTIONAL:

Add location and travel signs below the in-stave notation in staves 3-4 below.
**OPTIONAL** Recopy all in the empty staves.

**Comment by rsryman** [comment]
Done.
