### ISSUE TITLE
ebook versus name of the book

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#48]
Sis, in BB3 Worksheets you went through and changed ebook to _Book 3_ when it referred to just book 3.
To be consistent, do you think you could do the same in BB4 Worksheets?
I only found 2 places (pages 37 and 38) when I searched the pdf.
Page 36 uses ebook, but you are talking about all the ebooks in this case so it should remain as is.

**Comment by rsryman** [comment]
I changed "the ebook" to "_Book 4_" on pp. 37-38.

**Comment by rryman** [comment]
- [ ] Page 37 - add "in" to match page 38

The sequence below is notated in two ways: showing the number of empty bars (6) as **in** Book 4 on p. 95, versus the bar numbers (Bars 2-7) as shown below. Note that the first example is shrunk slightly to fit on one stave.

**Comment by rryman** [comment]
I did bold it! You just missed the "in" before **in** _Book 4_

The sequence below is notated in two ways: showing the number of empty bars (6) as **in** _Book 4_ ...
