### ISSUE TITLE
Reduction in size of notation examples

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#50]
Rhonda, if you are looking for something to do while I continue to work on the Benesh for Ballet: Book 3 Writing Worksheets could you experiment with your version of the pdf for Benesh for Ballet: Book 4 and see if you can fix the size of the notation on pages 34, 37 (1st 2 examples), 38, and 44? 

Also check if there are any other corrections you want to make to your pdf before I start updating it. No hurry on this as it is going to take me quite awhile to update the Book 3 worksheets, but at least it will be ready for when I get to it.

**Comment by rsryman** [comment]
Not sure what you mean by experimenting. I use Adobe Reader so I can't edit the pdf. I can certainly create and upload .ps files of the MacBenesh clips on the pages you mention.

**Comment by rryman** [comment]
By experiment, I mean look at your original Word doc and your original MacBenesh files for Book 4. See if you can see what you did differently for the MacBenesh examples that have been reduced.
Most of the examples are fine, except for pages 34, 37 (1st two examples), 38, and 44.
Why is that? Look at one example that was not reduced and one example that has been reduced and see if you set different margins or whatever. I just don't understand why it is perfectly fine in some cases and not in others. We couldn't do anything about Book 3 Worksheets because I had already started editing, but if Book 4 could be fixed before I start that would be great!
