### ISSUE TITLE
BB4Formatting re CH6 pp.104-110

### ISSUE THREAD

**Issue by rsryman** [rryman/BB4-Worksheets#51]
When I reformatted the examples on p. 44, the larger staves made it impossible to fit 8 staves on the page. Possible solutions:
**OPTION 1**: add another page, which would change the rest of the pagination.
**OPTION 2**: use a similar format and instruction as we did re BB3 p.20: "Here are two alternate ways to notate this sequence. In the empty staves below copy one of the versions." This would use 6 staves per page so that each pair could be present on a single page.

Before I proceed, can we have a chat to discuss how to resolve this. For the 6 sequences on Book 4 pp. 104-110, we could have a generic explanation on Worksheets p. 40: 
"The paired examples in this chapter illustrate alternate ways to notate each sequence: the first shows each **path of travel**, and the second summarizes the overall **geometric pattern**. Unless otherwise stated, copy one version in the empty staves below, paying careful attention to the drawing and placement of below-stave staging information."

The wording covers exceptions on pp. 41 (different number of empty staves but lots of space) and 44 on, (other instructions). See the attached sample:

[BB4WorksheetsJan24,2019.pdf](https://github.com/rryman/BB4-Worksheets/files/2793881/BB4WorksheetsJan24.2019.pdf)

**Comment by rryman** [comment]
The instructions on page 40 are fine. I think giving them the option of just choosing one example to recopy is fine. 
Yes, new instruction needed for page 41 and 46, 47, 49?

**Comment by rsryman** [comment]
As per our phone call:
p. 41 : Rhonda moved the second notated version above the empty staves and spaced out all staves.
p. 44: Rhonda reworded  the note re OPTIONAL: 
Recopy all in the empty staves. -> Recopy the sequence in the empty staves.
pp. 46 & 49: For practice writing in-stave and below-stave information on diagonal travel, recopy the sequence fully notated below (without _repeat_ signs) in the empty staves.

**QUESTIONS** (should I open a new Issue?):
General: we seem to use "copy" versus "recopy" interchangeable. A problem?
Re p. 40: should we say "copy one version" or "copy either version"?
Re pp. 45, 47, 48: PLEASE CONFIRM:
Note sure we came to a conclusion on this, but I added the same instructions as on p. 44: 
"Add _location_ and _travel_ signs below the in-stave notation in staves 3-4 below.
OPTIONAL: Recopy the sequence in the empty staves."

Also, I did my best to reposition _travel_ signs that got "bumped" in- vs between-frames, so they are as close as possible to the ebook format.

[BB4WorksheetsJan26,2019.pdf](https://github.com/rryman/BB4-Worksheets/files/2799384/BB4WorksheetsJan26.2019.pdf)

**Comment by rryman** [comment]
- [ ] pp. 46 & 49: What about?

To practice writing in-stave and below-stave information for diagonal travel, in the empty staves below, copy the sequence fully notated (without repeat signs).

**Comment by rryman** [comment]
- [ ]  Re p. 40: should we say "copy one version" or "copy either version"?
**copy either version**

**Comment by rryman** [comment]
Re pp. 45, 47, 48: PLEASE CONFIRM:
Note sure we came to a conclusion on this, but I added the same instructions as on p. 44:
"Add location and travel signs below the in-stave notation in staves 3-4 below.
OPTIONAL: Recopy the sequence in the empty staves."

- [ ] Page 44 - change "recopy" to "copy" if that's what we decide to do consistently - see issue
Copy/Recopy/Rewrite #52

- [ ] Page 45 - remove instructions as they are the same as page 44.

- [ ] Page 47 - keep the instructions as they are different from page 46 (copy not recopy?).

- [ ] Page 48 - remove instructions as they are the same as page 47.

Philosophy - don't restate the instructions unless they differ from the previous instruction.

**Comment by rryman** [comment]
- [ ] Rhonda to change text on pages  46 & 49 to:

To practice writing in-stave and below-stave information for diagonal travel, copy the sequence fully notated (without repeat signs) in the empty staves below.
