### ISSUE TITLE
Copy/Recopy/Rewrite

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#52]
**Rhonda:** We seem to use "copy" versus "recopy" interchangeable. A problem?
**Robyn:** I noticed this is a problem in Book 3 Worksheets as well. You also used "rewrite" and "re-write" when the student is asked to notate the sequence on the other side. 

I did a search in worksheets for 1 and 2 and we mainly use the word "copy" or "copying".

What do you think about consistently using the word "copy" in Books 3 and 4?
Is it okay to say "copy on the other side", or should we say "rewrite on the other side"?

**Comment by rsryman** [comment]
You make a valid distinction. Let's consistently say "copy" when it's exact, but "rewrite" when it's other side.

Please update your pdf for Book 3 Worksheets and I'll do a global search and replace on the .doc files for Books 3 and 4 Worksheets. Or do you want to do this together? I'll wait to hear.

**Comment by rsryman** [comment]
I will update my BB4 .doc file.

I will wait until you send me your updated BB3 .pdf file to proofread and update my BB3 .doc file.

**Comment by rsryman** [comment]
Re  BB4 Worksheets: there were no instances of "re-write" or rewrite." 
I replaced "recopy"  with "copy" 4 times: pp. 8, 30, 31, 44.
p. 8 Start by tracing the grey notation (the Benesh signs only, not the stave lines or bar lines), then recopy each position into the frames with and without a dotted centre line.
p. 30 Add locomotion lines to staves 3-4, then recopy all in staves 5-6. 
p. 31 Add locomotion lines to staves 3-4, then recopy all in staves 5-6.
p. 44 OPTIONAL: Recopy all in the empty staves.
