### ISSUE TITLE
Time signatures and Tempos

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#57]
Rhonda used a different font for time signatures and tempos in the worksheets for _Book 4_.
Robyn will change the font to match the other sets of worksheets.

**Time Signatures**
From Times Bold 17.39 pt 
To Arial Regular 18 pt

**Tempos**
From Times Regular 10.87 pt
To Arial Regular 10 pt

**Comment by rsryman** [comment]
I can't understand this comment, since don't have such fine control over font size, in either MacBenesh or Word 6.

Please clarify and I will try to fix this in the pdf I give you.

**Comment by rryman** [comment]
Rhonda will change fonts to Arial in her MacBenesh files and update the Word .doc.

**Comment by rsryman** [comment]
Robyn to confirm that fonts on p. 28 are correctly updated. 
Also, note that I have used double bar lines instead of final double bar lines to create better formatting.

[BB4p28Feb5,2019.pdf](https://github.com/rryman/BB4-Worksheets/files/2834104/BB4p28Feb5.2019.pdf)

**Comment by rryman** [comment]
This now matches the fonts used in worksheets for Book 3.
I will fix the lengths of the staves in Adobe Illustrator so they match.

BTW, do you have a preference for italicizing _bar_ line or _double bar_ line, or not italicized?
I noticed in the worksheets for Book 3 we have one italicized _bar_ line, and two regular bar lines.
We don't italicize _stave_ lines. Is that okay?

**Comment by rsryman** [comment]
I think we decided to use regular (not italics) for bar line/s and stave line/s. 

Re BB3 Worksheets p. 22, change "_bar_ lines" to "bar lines":

- [ ] Robyn to update the pdf in Adobe Illustrator  

- [ ] Rhonda to update the .doc file.

**Comment by rryman** [comment]
I think there are a couple of places where the number of repeats are not Arial, nor is the text for the number of bars. I can easily update them in Adobe Illustrator, but if you'd prefer to do it at your end let me know and I will go through the PDF carefully when I am at my computer and enter the page numbers in GitHub.

**Comment by rsryman** [comment]
Thanks for your careful reading. My eyes are really strained. 

Yes please send a list of fonts still to be changed so I can fix them in MacBenesh and the .doc file. I have to change the footer and add a blank page before the page of staves anyways.

Also, I think it would be better for you to add the text, if you can just copy BB3 Worksheets p. 61 into the blank page BB4 Worksheets p. 50. I have noted this in Issue #60

**Comment by rryman** [comment]
Dimensions of Curved Travel (Book 4 p. 94)
- [ ] p. 37 - top stave, number of repeats - **3**
- [ ] p. 37 - top stave - **Bars 2-4**

Dimensions of Circular Travel (Book 4 p. 95)
- [ ] p. 37 - second last stave - **Bars 2-7**

Dimensions of Other Paths of Travel (Book 4 p. 96)
- [ ] p. 37 - second last stave - **Bars 2-7**

Curved Travel with Entrance and Exit (Book 4 p. 97)
- [ ] p. 39 - top stave  - **Prep.**
- [ ] p. 39 - top stave, number of repeats - **6**
- [ ] p. 39 - second stave - **7 Bars**

Travel Forward (Book 4 p. 104)
- [ ] p. 40 - first stave - **Bars 2-3**
- [ ] p. 40 - second stave - **Bars 4-7**, **Bars 8-10**, **Bars 11-14**
- [ ] p. 40 - third stave - **Bars 2-14**

Travel Backward (Book 4 p. 105)
- [ ] p. 41 - third stave - **Bars 2-4**
