### ISSUE TITLE
Date for Footer

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#59]
How about putting May 2019 as the copyright date in the footer for Book 4?

**Comment by rsryman** [comment]
BB3 Worksheets footer says March 2019 and they are ready in February.
Do you think it will take almost 2 months to do BB4?
What about April 2019 for BB4 Worksheets?

**Comment by rryman** [comment]
By the time Canan looks at BB3 worksheets and gets back to us and I upload them to the server, it could well be March. Does it really matter?

**Comment by rsryman** [comment]
- [ ] Rhonda to change footer to May 2019

**Comment by rryman** [comment]
Rhonda, I just realized that I had previously done quite a lot of work on the writing worksheets for Book 4. I still have to copy and paste each of the pages I had previously updated with the stage plan and stage location information, but quite a bit of the time consuming work has been done on this first section of the worksheets.

So if you want to use April 2019 for the footer, go ahead. I don't really think it matters, but I will leave it up to you.

**Comment by rsryman** [comment]
Easy enough to make this change to April 2019 before I upload today's pdf.

- [ ] Rhonda to change footer to May 2019

**Comment by rryman** [comment]
Did you mean to type...

- [ ] Rhonda to change footer to **April** 2019

**Comment by rsryman** [comment]
Duh, yes, just did that, ready to upload.
