### ISSUE TITLE
BB4TyposTo Correct

### ISSUE THREAD

**Issue by rsryman** [rryman/BB4-Worksheets#63]
- [x] Robyn to correct pdf file

- [x] Rhonda to correct doc file

p. 18 line 1 typo: 
Note that location and travel signs are combined to show **entances** -> entrances

p. 21 2 typos: 
Travel sideways left, clockwise, 1 full circle, **srart** and end facing stage right ->
Travel sideways left, clockwise, 1 full circle, start and end facing stage right

Travel sideways left, counterclockwise, 1 full circle, **srart** and end facing stage right ->
Travel sideways left, counterclockwise, 1 full circle, start and end facing stage right

**Comment by rryman** [comment]
Above corrected in this pdf:
[BB4Worksheets8FebP23.pdf](https://github.com/rryman/BB4-Worksheets/files/2846658/BB4Worksheets8FebP23.pdf)

Please close this issue if you are happy with this update.

**Comment by rsryman** [comment]
May we keep this item open rather than open separate issues for specific page typos? I also found:

p. 4 In this lesson, we focus on drawing stage plans and location signs. Later, we learn how to correlate _**locations**_ signs -> _location_ signs

**Comment by rryman** [comment]
P. 4 typo updated in this pdf:
[BB4Worksheets8FebP25.pdf](https://github.com/rryman/BB4-Worksheets/files/2846779/BB4Worksheets8FebP25.pdf)

**Comment by rryman** [comment]
- [ ] Rhonda to close this issue if she is happy with these corrections.
