### ISSUE TITLE
Double Bar Lines - pages 24 and 25

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#64]
We don't seem to use double bar lines unless the sequence is to music, or there is more than one sequence on one continuous stave. So to be consistent I have taken out the double bar lines on pages 24 and 25 of the attached pdf. I think it looks cleaner.

[BB4Worksheets8FebP25.pdf](https://github.com/rryman/BB4-Worksheets/files/2846702/BB4Worksheets8FebP25.pdf)

**Comment by rsryman** [comment]
Agreed. I've update the doc file.

**Comment by rryman** [comment]
I'll do the same for page 29 when I reach it.
