### ISSUE TITLE
Page 31 (Book 4 P. 82)

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#68]
Corrections made to the file attached below to be checked by Rhonda (and to be updated in original .doc and MacBenesh files?):

- [x] Space added between p. and 82)
- [x] In first sentence, text changed "notated below with **part-bar** _repeat_ signs."
- [x] In second sentence, "staves 3-4" changed to "stave 3" as there are no locomotion lines in stave 4 to be added.
- [x] **With repeats** text deleted ... doesn't seem necessary given the first sentence.
- [x] In both examples, starting position, 5th position corrected (now right foot in front).

[BB4WorksheetsP31.pdf](https://github.com/rryman/BB4-Worksheets/files/2877371/BB4WorksheetsP31.pdf)

**Comment by rsryman** [comment]
All good.

**Comment by rryman** [comment]
Can this issue be closed now?
