### ISSUE TITLE
Page 32 (Book 4 pp. 84 & 85)

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#70]
- [x] Rhonda to check this page carefully. Robyn made quite a lot of tiny adjustments to the notation to try to have the notation in each example line up.

- [x] Rhonda to confirm the size, shape, and placement of the travel sign. Is this okay?
This will ripple through the rest of the pages as all the travel signs are bitmapped in MacBenesh and have to be replaced.

[BB4WorksheetsP32.pdf](https://github.com/rryman/BB4-Worksheets/files/2880819/BB4WorksheetsP32.pdf)

**Comment by rsryman** [comment]
Re Classical Walks, 2 examples on stave 3  (2nd stave of notation examples):
1. perhaps move the ad lib dots a bit to the left?
2. attachment of the 2 step lines to the right foot looks more centred in the examples on stave 1

Re Natural Walks:
1. please update all 4 starting positions: delete two-feet-together-level signs and move up toe caps
2. the 2 forward travel arrows look a bit too thick; shape is fine; placement is good although would it look better to align the shaft of the arrow with the in front sign in the first example, as p. 85 Ex. 3?

**Comment by rsryman** [comment]
Re **Specific Versus Non-Specific Timing - Classical Walks** (Book 4 p. 84): the ad lib signs in the ebook appear closer to the basic signs than the two examples in the Worksheets p. 32. The two examples re **Natural Walks** are fine (bottom of p. 32).

**Comment by rryman** [comment]
- [ ] Rhonda to check the corrected spacing of the _ad lib_ signs in the attached pdf of page 32.

[BB4WorksheetsP32.pdf](https://github.com/rryman/BB4-Worksheets/files/2901502/BB4WorksheetsP32.pdf)
