### ISSUE TITLE
Instructions on pages 37 and 38

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#71]
We have been trying not to duplicate instructions. Do you think we should make the instructions on page 37 more generic and then not repeat them on page 38? Or just leave it as is?

**Comment by rsryman** [comment]
Basically the same instruction except for the page reference, which is also in the title/heading.
I don't know how we can make p. 37 more generic (I think the mention of the specific number of bars is helpful) , but we could just delete the instructions on p. 38 and trust that students can apply the gist from the previous page, as they have done before. I'm happy either way.

**Comment by rryman** [comment]
Here is what I had in mind to make it more generic so the same instructions need not be repeated on the next page:

The sequence below, and on the next page, are notated in two ways: showing the number of empty bars (6) as in Book 4, versus the bar numbers (Bars 2-7) as shown below. Note that in the first example the bars are compressed to fit on one stave.

**Comment by rsryman** [comment]
Good idea. Small suggested revisions (take out 2 commas in line 1; rewording shown in **bold**):

The sequence below and on the next page are **each** notated in two ways: **first** showing the number of empty bars (6) as in _Book 4_, **then** showing the bar numbers (Bars 2-7). Note that in **each** first example the bars are compressed to fit on one stave.
