### ISSUE TITLE
Part-bar Repeat Signs

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#75]
In the attached page I have changed the spacing of the inside repeat line (the one that fits in the 5 line stave) to:
2 pt 3 pt 2 pt 3 pt 2 pt 2 pt
and for the outside repeat lines (the ones that extend outside the 5 line stave) to:
2 pt 3 pt 2 pt 3 pt 2 pt 3 pt

I have made the line widths for both the repeat lines and the markings to be:
0.5 pt

[BB4WorksheetsP45B5M5.pdf](https://github.com/rryman/BB4-Worksheets/files/2942836/BB4WorksheetsP45B5M5.pdf)

**Comment by rryman** [comment]
I tried creating my own dashed lines in Adobe Illustrator, but it is a nightmare!

**Comment by rsryman** [comment]
Robyn, the page you sent me looks crystal clear on the screen, and prints crystal clear on my laser printer.

No need to make this any more "beautiful"!
