### ISSUE TITLE
Page 3 of all Worksheets

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#77]
Rhonda is getting feedback from Canan about adding printing instructions to page 3 of all the worksheets.

**Comment by rryman** [comment]
- [ ] Rhonda please check this wording for Page 3 of the worksheets. I have moved the printing information together at the end of the other information and changed the wording of the alert a little.
Once we have agreed on the wording, I will have to redo all the text for page 3. I should be able to copy the text from here and update the pdf in Adobe Illustrator. I will probably have to fiddle with the layout to make it all fit.

Page 3 wording:

These worksheets are intended to give you practice writing Benesh Movement Notation (BMN).
This will help you master BMN principles for staging information.
There is no need to complete every question. Rather, complete as much of each lesson as you feel you need to master the new signs introduced.
In order to reinforce your ability to read BMN, you should stand up and perform each position before attempting to copy it.
Don't copy blindly, but rather make sure you understand each notated sequence and the relevant Benesh theory.
If you feel confident, you may copy any of the examples onto red-lined stave paper.
A printable pdf is provided at the end of these worksheets.
ALERT: To print these worksheets without shrinkage on US letter or A4 paper, be sure that you select "No Scaling" or "100%." (The exact wording in your printer dialogue box will depend on your application and operating system.)

**Comment by rryman** [comment]
Here is an example of an updated Page 3: 
[BB4WorksheetsP3.pdf](https://github.com/rryman/BB4-Worksheets/files/2948542/BB4WorksheetsP3.pdf)

I found a way to control the space between the lines. Let me know if you think they should be spread further apart.

**Comment by rsryman** [comment]
I think it looks fine and like your wording updates, but I don't like how the brackets look. What about:

ALERT: To print these worksheets without shrinkage on US letter or A4 paper, be sure that you select "No Scaling" or "100%." Note that the exact wording in your printer dialogue box will depend on your application and operating system.
