### ISSUE TITLE
Canan's Corrections

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#78]
Rhonda, please check these corrections before I send the updated worksheets to Canan, upload them to the server, and distribute the URL.

- [x] p.16: The upstage sign at "Travel Diagonally".
Robyn fixed incorrect travel backwards upstage sign.
- [x]   p.17: The 4 at (Book 4 p. 43).
Robyn fixed italic 4.
- [x]   p. 21: The 4 at (Book 4 pp. 57-58).
Robyn fixed italic 4.
- [x] p. 21:  Clockwise at the 8th box should be counterclockwise.
Robyn added "counter".
- [x] p. 22: The 4 at (Book 4 p. 59).
Robyn fixed italic 4.
- [x] p. 24: I think you changed the explanations to the top of the stave at Book3. Like "Jump sur place into 4th". If so also on page 25.
Robyn updated text to 12 pt and shifted captions above notation.
Rhonda, please check these two pages carefully as I had to retype the captions.
- [x] p. 32: Above stave information such as "Walk forward on count one"?
Robyn did not add the captions to this page. I think it would make it very squished or require us to split this over two pages. Rhonda, please look at this page and let me know if you still agree with leaving it as is.

[BB4_Book4_Worksheets.pdf](https://github.com/rryman/BB4-Worksheets/files/3034359/BB4_Book4_Worksheets.pdf)

**Comment by rsryman** [comment]
p. 16: I also noticed a subscript opening bracket to be fixed before the word "Book" :
Travel Diagonally Facing Front - Stage Plans (Book 4 p. 42)

**Comment by rryman** [comment]
I fixed the bracket on p. 16.
Am I correct in assuming we are leaving p. 32 as is, because you ticked it off?
If so, are we good to go with this set of worksheets?

[BB4_Book4_Worksheets.pdf](https://github.com/rryman/BB4-Worksheets/files/3038614/BB4_Book4_Worksheets.pdf)

**Comment by rsryman** [comment]
I'm ok with p. 32 as is. As you said, we want these worksheets to reinforce and accompany but not replace the ebooks.
